### ISSUE TITLE
Question : Should we start Pandas.NET in NumSharp repo?

### ISSUE THREAD

**Issue by dotChris90** [Oceania2018/Pandas.NET#1]
It is totally great to start Pandas.NET. 

But maybe we should discuss to make it as a project in NumSharp. 

So the structure (of big picture in future) would be like that : 

Repo NumSharp (maybe we can call it later as "NumSharpStack" so it is clear all libraries that bases on NumSharp). 

/src/NumSharp/Numsharp.csproj
/src/Pandas.NET/Pandas.NET.csproj
/src/SciSharp/SciSharp.csproj

The reason for that is --> at moment we are still under construction. 
If NumSharp change we do not know what impact it has for Pandas.NET. Moreover 
at moment we could build all stuff with command "dotnet build" and we do not depend on
Nuget package. 

But thats up to u. :)

**Comment by Oceania2018** [comment]
Combine into one big project might make things complicated, and have new contributor difficult to start working. Have pros and cons, let's separate them first. We might contribute them into an organization. Don't think about it too much. Let's just make the two projects are valuable to .NET developers.

**Comment by dotChris90** [comment]
Ok agree.

Should we start a Organisation / group `NumSharpStack` or something else in future and move repos to this?

So all other libraries will be added there too?

- NumSharp
- pandas.net
- MatPlotSharp
- SciSharp

It would be easier for others to see what libraries exist already.
:)

Just a suggestion. And I know we are at start. But I am surprised how fast all grown and already feel very nice. So want to do this suggestion. ;)

**Comment by Oceania2018** [comment]
Adopt to an ORG is a good option. I've a connection with [.NET Core Community](https://github.com/dotnetcore), and I've contributed the [BotSharp](https://github.com/dotnetcore/BotSharp) to NCC. It would be great if you have connection with other .NET community, we might consider about it. But I'm think it's too early so far.

**Comment by dotChris90** [comment]
Hm yes got ur point. At moment I don't mind where to push. So it's OK. :)
